# -*- coding: utf-8 -*-
"""bar chart race.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jBnXkh8ldACJkBASGzk-pfcccYYrFvd3
"""

import yfinance as yf

msft = yf.Ticker("^NSEBANK")

# get all stock info
msft.info

# get historical market data
hist = msft.history(period="5y")

import pandas as pd
df=pd.DataFrame(hist)

# Calculate the difference between consecutive rows
df['diff'] = df['Close'].pct_change()*100

df.reset_index(inplace=True)

# Extract day of the week
df['day_of_week'] = df['Date'].dt.strftime('%A')

df

!pip install bar_chart_race

import bar_chart_race as bcr

df=df[['diff','day_of_week','Date']]
df['diff']=abs(df['diff'])

df

# Convert 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Set 'Date' as index
df.set_index('Date', inplace=True)

# Pivot the table
df_pivot = df.pivot(columns='day_of_week', values='diff')

# Reset the index
df_pivot['Date'] = df_pivot.index
df_pivot.reset_index(drop=True, inplace=True)
df_pivot

df_pivot=df_pivot[['Date','Monday','Tuesday','Wednesday','Thursday','Friday']]

df_pivot

df_bcr=df_pivot.copy()

df_bcr

df_bcr=df_bcr.fillna(0)
df_bcr['Monday']=df_bcr.groupby(df_bcr['Date'].dt.year)['Monday'].cumsum()
df_bcr['Tuesday']=df_bcr.groupby(df_bcr['Date'].dt.year)['Tuesday'].cumsum()
df_bcr['Wednesday']=df_bcr.groupby(df_bcr['Date'].dt.year)['Wednesday'].cumsum()
df_bcr['Thursday']=df_bcr.groupby(df_bcr['Date'].dt.year)['Thursday'].cumsum()
df_bcr['Friday']=df_bcr.groupby(df_bcr['Date'].dt.year)['Friday'].cumsum()

df_bcr

df_bcr.set_index('Date',inplace=True)

df_bcr.isnull().sum()

df_bcr.info()

bcr.bar_chart_race(df=df_bcr,orientation='v',filename ='bar.mp4',interpolate_period=True, period_label = {'x':.75, 'y': .1}, title = 'Most Volatile days of Nifty Bank 2019-2024')

+